languageCode = "en-us"
baseurl = "https://timefrancesco.github.io/bitfolio"
title = "Bitfolio"

[Params]
	description = "Keep an eye on the crypto world and track your assets"
	ios_id = "1264391689"
	logo = "img/new-website-cover.png"
	twitter = "bitfolioapp"
	facebook = "bitfolioapp"
	flickr = "useless it's just used to show the info image so that directs to FAQ"
