languageCode = "en-us"
baseurl = "https://timefrancesco.github.io/bitfolio"
title = "Bitfolio"

[Params]
	description = "Crypto currencies ticker & portfolio"
	ios_id = "1264391689"
	logo = "img/new-website-cover.png"
	twitter = "bitfolioapp"
